[[module.imports]]
path = "github.com/hbstack/hb"

[[module.imports]]
path = "github.com/hugomods/icons/vendors/bootstrap"

[[module.imports]]
path = "github.com/henrygd/bigger-picture"
[[module.imports.mounts]]
source = "dist"
target = "assets/mods/bigger-picture"

[params.hb.bigger_picture]
play_interval = 5000 # in milliseconds.
scale = 2
